CREATE TABLE Product (
    ProductID INT IDENTITY PRIMARY KEY,
    Name VARCHAR (50),
    Price FLOAT
);

CREATE TABLE City (
	CityID INT IDENTITY PRIMARY KEY,
	Name VARCHAR(50) NOT NULL,
	State VARCHAR(50) NOT NULL
);

CREATE TABLE Customer (
    CustomerID INT IDENTITY PRIMARY KEY,
    CityID INT NOT NULL, 
    FirstName VARCHAR (50) NOT NULL,
    LastName VARCHAR (50) NOT NULL,
    CONSTRAINT FK_CityID FOREIGN KEY (CityID) REFERENCES City (CityID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE Sale (
    SaleID INT IDENTITY,
    CustomerID INT NOT NULL,
    ProductID INT NOT NULL,
    Price FLOAT,
    Amount INT,
    CONSTRAINT FK_CustomerID FOREIGN KEY (CustomerID) REFERENCES Customer (CustomerID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_ProductID FOREIGN KEY (ProductID) REFERENCES Product (ProductID) ON DELETE CASCADE ON UPDATE CASCADE, 
    CONSTRAINT PK_Sale PRIMARY KEY (SaleID, CustomerID, ProductID)  
    
);
CREATE TABLE Comment (
    CommentID INT IDENTITY PRIMARY KEY,
    CustomerID INT NOT NULL,
    SaleID INT NOT NULL,
    Date_comment Date,
    CommentText VARCHAR(50),
    CONSTRAINT FK_CustomerID_Comment FOREIGN KEY (CustomerID) REFERENCES Customer (CustomerID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_SaleID FOREIGN KEY (SaleID) REFERENCES Sale (SaleID) ON DELETE CASCADE ON UPDATE CASCADE  
);

CREATE TABLE Factor(
    FactorID INT IDENTITY PRIMARY KEY,
    Name VARCHAR (50), 
    Percentage VARCHAR (50)
);